version: "3.9"

services:
  taiwan:
    build: .
    environment:
      - INDEX=TAIWAN
      - TELEGRAM_TOKEN=your_telegram_bot_token
      - TELEGRAM_CHAT_ID=your_chat_id
    command: ["python", "bot_action.py"]
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
    schedule:
      - cron: "3 11 * * 1-5"    # Taiwan 11:03am

  kospi:
    build: .
    environment:
      - INDEX=KOSPI
      - TELEGRAM_TOKEN=your_telegram_bot_token
      - TELEGRAM_CHAT_ID=your_chat_id
    command: ["python", "bot_action.py"]
    restart: always
    schedule:
      - cron: "2 12 * * 1-5"    # Kospi 12:02pm

  hangseng:
    build: .
    environment:
      - INDEX=HANGSENG
      - TELEGRAM_TOKEN=your_telegram_bot_token
      - TELEGRAM_CHAT_ID=your_chat_id
    command: ["python", "bot_action.py"]
    restart: always
    schedule:
      - cron: "41 13 * * 1-5"   # Hang Seng 01:41pm

  sensex:
    build: .
    environment:
      - INDEX=SENSEX
      - TELEGRAM_TOKEN=your_telegram_bot_token
      - TELEGRAM_CHAT_ID=your_chat_id
    command: ["python", "bot_action.py"]
    restart: always
    schedule:
      - cron: "31 15 * * 1-5"   # Sensex 03:31pm

  dax:
    build: .
    environment:
      - INDEX=DAX
      - TELEGRAM_TOKEN=your_telegram_bot_token
      - TELEGRAM_CHAT_ID=your_chat_id
    command: ["python", "bot_action.py"]
    restart: always
    schedule:
      - cron: "8 21 * * 1-5"    # DAX 09:08pm

  dowjones:
    build: .
    environment:
      - INDEX=DOWJONES
      - TELEGRAM_TOKEN=your_telegram_bot_token
      - TELEGRAM_CHAT_ID=your_chat_id
    command: ["python", "bot_action.py"]
    restart: always
    schedule:
      - cron: "31 1 * * 2-6"    # Dow Jones 01:31am (Tue–Sat)
