name: Hang Seng
on:
  schedule:
    - cron: "41 08 * * 1-5"   # 01:41 PM IST = 08:11 UTC  ➜ tumhare schedule ke hisaab se set karo
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run job
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID:  ${{ secrets.CHAT_ID }}
          INDEX:    HANGSENG
        run: python bot_action.py
