name: KOSPI
on:
  schedule:
    - cron: "32 6 * * 1-5"   # 06:32 UTC = 12:02 IST
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt
      - name: Run job
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID:  ${{ secrets.CHAT_ID }}
          INDEX:    KOSPI
        run: python bot_action.py
